#### 
# Register User
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "David Njenga",
  "email": "david@gmail.com",
  "password": "JanetAlwanga@1!",
  "isAdmin": 1
}
#### Login User
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "sistee001@gmail.com",
  "password": "JanetAlwanga@1!"
}
// get all the users
######
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMxMjAzLCJleHAiOjE3MTg2Mzg0MDN9.XELymKrYQ885sNgAhiy1KChix4fhGYXEX857iC4SSnM
//Add Tours
####
POST http://localhost:4000/tours
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w
Content-Type: application/json

{
  "name": "Samburu",
  "description": "get to experience buffalo springs in samburu",
  "price": 1000,
  "duration": 3
}
// Get all tours
####
GET http://localhost:4000/tours
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w

#### get a single tour
GET http://localhost:4000/tour/0a5c3157-7df6-4a47-adee-44da671a47af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w


// add hotel
####
POST http://localhost:4000/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzIwMDA5MTkzLCJleHAiOjE3MjAwMTYzOTN9.cwem57S_6KZVJA2GMfmSjtH_ieljqoZIgFCUBKpe3Tc
Content-Type: application/json

{
  "name": "Merica Hotel",
  "location": "Nakuru",
  "price": 1500,
  "imageUrl":"https://images.trvl-media.com/lodging/30000000/29030000/29027900/29027886/eeccc081_z.jpg"
}

//Get all hotels
####
GET http://localhost:4000/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w

// add booking
####
POST http://localhost:4000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE5MTMzNjU3LCJleHAiOjE3MTkxNDA4NTd9.6eDBMFPqGgaHkqTIib8Jbhe1A_dazQp2qEdpRaGjMzw
Content-Type: application/json

{
  "userId": "ea0c7593-1b92-4725-83b4-2191dcfdb424",
  "tourId": "39a60bcf-7c4d-4459-9557-111c2ae725ad",
  "hotel_Id": "9f4bcbaa-17ed-41ac-bb33-bc294a573652"
}

//Get all bookings
#####
GET http://localhost:4000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4Nzg3MjA3LCJleHAiOjE3MTg4MDUyMDd9.pmBc0yZrcAKLIW6807HQizBhM-QSH4QQYaJn_KsqQuQ

// Get a single booking
####
GET http://localhost:4000/bookings/23be406c-aa5a-4add-8b45-577a95ad2367
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE5MTMzMzY5LCJleHAiOjE3MTkxNDA1Njl9.iSA-6pVvtJBL8-ITrkyzNfLUJSFV_S0b3fnr8d9AvRo

### Update Booking
PUT http://localhost:3000/bookings/23be406c-aa5a-4add-8b45-577a95ad2367
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE5MTMzMzY5LCJleHAiOjE3MTkxNDA1Njl9.iSA-6pVvtJBL8-ITrkyzNfLUJSFV_S0b3fnr8d9AvRo
Content-Type: application/json

{
  "status": "confirmed"
}
